# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://epicoursebogota.netlify.com"
languageCode = "en-AU"
title = "Epidemics analysis short course"

# Metadata
[params]
  author = "Thibaut Jombart"
  description = "Website of the RECON short course on epidemics analysis and response, Bogota, December 2017"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/bg_bogota.jpg"
  title = "Epidemics Analysis, Modelling and Response"
  description = "Short Course, Bogota, 11-15 December 2017"

# Navigation section
[params.nav]
  mission = "Practical info"
  services = "Content"
  team = "Teachers"
  contact = "Register"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/compass.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/calendar.jpg"

  [[params.mission.item]]
    weight = 1
    name = "location"
    title = "Location"
    subtitle = 'The course will be hosted at the Universidad Nacional de Colombia, Bogota. The exact location will be confirmed closer to the event.'
    description = '<p>Here is a map of the campus:<br><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3976.7524465035945!2d-74.08623508491984!3d4.638193796630703!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3f9bd14943c13b%3A0x3de530667d9ff6b0!2sUniversidad+Nacional+de+Colombia!5e0!3m2!1sen!2suk!4v1507557470825" width="450" height="450" frameborder="1" style="border:0" allowfullscreen></iframe></p>'

  [[params.mission.item]]
    weight = 2
    name = "date"
    title = "Date"
    subtitle = "The course will take place over 5 days, 11-15 December 2017"
    description = ""

  [[params.mission.item]]
    weight = 3
    name = "register"
    title = "Register"
    subtitle = "Please use the google form below to register. Deadline for registration is 10th November 2017."
    description = '<p>To register for the short course, you need to send your application the google form below <a href="https://docs.google.com/forms/d/e/1FAIpQLSfJXzgrRid4HuUbvBr2Qkw8JvFAyP2lpfCxxvE43i-cA3NXqw/viewform?usp=sf_link">[full page]</a>:</p><br><p><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfJXzgrRid4HuUbvBr2Qkw8JvFAyP2lpfCxxvE43i-cA3NXqw/viewform?embedded=true" width="500" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe></p>'
 
  [[params.mission.item]]
    weight = 4
    name = "contact"
    title = "Contact"
    subtitle = "If you would like to register for the course, please go to the 'register' section and use the form provided. To ask questions about the course, use the contacts provided below."
    description = "<p><ul><li>contact Bogota: <a href='mailto:llopezk@unal.edu.co'>Liliana Lopez-Kleine</a></li><li>contact London: <a href='mailto:thibautjombart@gmail.com'>Thibaut Jombart</a></ul></p>"

  [[params.mission.item]]
    weight = 5
    name = "scholarships"
    title = "Scholarships"
    subtitle = "If you need financial support for travel and accommodation to attend the course, you can apply to a scholarship for this course. See the relevant section in the registration form (see 'register' section)."
    description = ""



# Services section
[params.services]
  enable = true
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Content of the course"
  description = "The course will provide an introduction to modelling and statistical techniques for analysing infectious disease epidemics. The methods presented will include tools for visualising epicurves, estimating transmissibility, deriving short term predictions of incidence, modelling infectious disease dynamics and assessing the impact of intervention strategies. The course will consist of lectures during the mornings and hands-on practical in the afternoon. All practicals will be using the R software. A basic knowledge of R will be assumed from the participants."

  # [[params.services.item]]
  #   icon = "icon-present"
  #   title = "Web Development"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = ""
    title = "R refresher"
    description = "<p><b>Monday 11/12/2017 7:00 - Statistics Department UNAL, room 208</b></p><p>Practical introduction to R. Non-experienced R users are required to attend this session.</p><br><br>"

[[params.services.item]]
    icon = ""
    title = "Opening seminar (public)"
    description = "<p><b>Monday 11/12/2017 10:00<br>Facluty of Science UNAL, Juan Herkrath auditorium</b></p><p>On the roles of statistics and modelling for informing outbreak response: examples from the West African Ebola outbreak and from the Zika epidemic.</p>"

  [[params.services.item]]
    icon = ""
    title = "Lecture 1"
    description = "<p><b>Monday 11/12/2017 13:00<br>Statistics Department UNAL, room 209</b></p><p>An introduction to infectious disease outbreak response: what data, what questions, and how to answer them?</p><br><br>"

 [[params.services.item]]
    icon = ""
    title = "Practical 1"
    description = "<p><b>Monday 11/12/2017 15:00<br>Statistics Department UNAL, room 208</b><p> Estimation of key delays, doubling time and transmissibility, short-term forecasting. R packages:<i> incidence, distcrete, epitrix, EpiEstim2, earlyR, projections</i></p>"

  [[params.services.item]]
    icon = ""
    title = "Lecture 2"
    description = "<p><b>Tuesday 12/12/2017 10:00<br>Statistics Department UNAL- room 209</b></p>Modelling epidemics using compartmental models 1: ‘simple’ models for directly transmitted diseases.</p>"

  [[params.services.item]]
    icon = ""
    title = "Practical 2"
    description = "<p><b>Tuesday 12/12/2017 13:00<br>Statistics Department UNAL- room 208</b></p><p>Modelling an Ebola outbreak and the impact of control strategies. R packages:<i> odin, DeSolve</i></p><br><br>"

  [[params.services.item]]
    icon = ""
    title = "Lecture 3"
    description = "<p><b>Wednesday 13/12/2017 10:00<br>Statistics Department UNAL- room 209</b></p><p>Modelling epidemics using compartmental models 2: applications to vector-borne diseases.</p>"

  [[params.services.item]]
    icon = ""
    title = "Practical 3"
    description = "<p><b>Wednesday 13/12/2017 13:00<br>Statistics Department UNAL- room 208</b></p><p>Using compartmental models to model the spread of arboviruses. R packages: <i>odin, DeSolve</i></p>"

  [[params.services.item]]
    icon = ""
    title = "Social event"
    description = "<p><b>Wednesday 13/12/2017 evening</b></p><p>Dinner with the participants. Venue and time will be confirmed closer to the event.</p><br><br><br>"

  [[params.services.item]]
    icon = ""
    title = "Lecture 4"
    description = "<p><b>Thursday 14/12/2017 10:00<br>Statistics Department UNAL- room 209</b></p><p>Using genetic sequences for inferring infectious disease dynamics.</p>"

  [[params.services.item]]
    icon = ""
    title = "Practical 4"
    description = "<p><b>Thursday 14/12/2017 13:00<br>Statistics Department UNAL- room 208</b></p><p>Introduction to phylogenetics, and disease outbreak reconstruction using epidemiological and genetic data. R packages: <i>ape, phangorn, outbreaker2</i></p>"


  [[params.services.item]]
    icon = ""
    title = "Grant writing exercise"
    description = "<p><b>Friday 15/12/2017 10:00<br>Statistics Department UNAL- room 208</b></p><p>Participants will assemble into multidisciplinary teams, typically mixing public health officers, epidemiologists and methodologists, to formulate new projects in view of a grant application. The event will conclude with presentations of the projects and feedback from the panel.</p>"

 

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = "This short course is organised in collaboration between the National University of Colombia, Imperial College London, and the University of Sussex. Meet our teaching team below."

  [[params.team.item]]
    name = "Liliana Lopez-Kleine"
    position = "Professor, University Nacional de Colombia"
    description = "Multivariate analysis, exploratory statistics, bioinformatics and system biology."
    img = "images/liliana.png"
    # facebook = "#"
    # twitter = "#"
    # github = "#"


  [[params.team.item]]
    name = "Thibaut Jombart"
    position = "Lecturer, Imperial College London"
    description = "Genetic epidemiology and outbreak response. Head of the R Epidemics Consortium (RECON)."
    img = "images/thibaut.jpg"
    # dribbble = "#"
    github = "https://github.com/thibautjombart"
    twitter = "https://twitter.com/TeebzR"

  [[params.team.item]]
    name = "Pierre Nouvellet"
    position = "Reader, University of Sussex"
    description = "Infectious disease modelling and outbreak response, with emphasis in zoonosis and emerging threats. "
    img = "images/pierre.jpg"
    # facebook = "#"
    # twitter = "#"
    github = "https://github.com/pnouvellet"

  [[params.team.item]]
    name = "Zulma Cucunubá"
    position = "Research Associate, Imperial College London"
    description = "Modelling tropical disease dynamics and interventions. Member of the Vaccine Impact Modelling Consortium."
    img = "images/zulma.jpg"
    # facebook = "#"
    # twitter = "#"
    # github = "#"

  [[params.team.item]]
    name = "James Hayward"
    position = "Senior Administrator, Imperial College London"
    description = "Head administrator for the NIHR-HPRU, and logistics guru for the short course."
    img = "images/james.jpg"
    # facebook = "#"
    # twitter = "#"
    # github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = false
  title = "Register"
  message = "Bla bla bla"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>This course is co-funded by the Medical Research Council (MRC) Centre for Outbreak Analysis and Modelling, and the National Institute for Health Research - Health Protection Research Unit (NIHR-HPRU) for Modelling Methodology</small></p><p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a> Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a>. Website by <a href='https://sites.google.com/site/thibautjombart/'>Thibaut Jombart</a>.</small></p>"
  github = "https://github.com/reconhub/workshopbogota"
  
